name: firefuel
description: A Firebase Cloud Firestore architecture to fuel your application's growth!
version: 0.0.1
repository: https://github.com/SupposedlySam/firefuel

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3

dev_dependencies:
  test: ^1.17.11
  
import_sorter:
  comments: false

scripts: derry.yaml
