name: firefuel
description: A Firebase Cloud Firestore architecture to fuel your application's growth!
version: 0.0.1
homepage: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
import_sorter:
  comments: false

scripts: derry.yaml
