name: firefuel
description: A Firebase Cloud Firestore architecture to fuel your application's growth!
version: 0.0.1
repository: https://github.com/SupposedlySam/firefuel
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.5.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  stack_trace: ^1.10.0
  firefuel_core:
    git: 
      url: https://github.com/SupposedlySam/firefuel.git
      path: packages/firefuel_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4
  
import_sorter:
  comments: false

scripts: derry.yaml
