name: firefuel_core
description: The core classes required to run firefuel
version: 0.1.5
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel_core

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  equatable: ^2.0.7
  stack_trace: ^1.12.1
  universal_io: ^2.2.2

dev_dependencies:
  test: ^1.26.3

import_sorter:
  comments: false

scripts: ../../derry.yaml
