name: firefuel_core
description: The core classes required to run firefuel
version: 0.0.1
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel_core

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  stack_trace: ^1.10.0

dev_dependencies:
  test: ^1.17.11

import_sorter:
  comments: false

scripts: ../../derry.yaml
