name: firefuel
description: A Firebase Cloud Firestore library to fuel your application's growth!
version: 0.2.2
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel
homepage: https://github.com/SupposedlySam/firefuel
documentation: https://firefuel.dev

# Flutter/Dart versions: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos
environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  cloud_firestore: ">3.4.8 <5.0.0"
  dartz: ^0.10.0
  equatable: ^2.0.5
  firefuel_core: ^0.1.0
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  universal_io: ^2.0.4

dev_dependencies:
  fake_cloud_firestore: 1.2.4 #Regression in 1.3.0 breaks ordering
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

import_sorter:
  comments: false

scripts: ../../derry.yaml
