name: firefuel
description: A Firebase Cloud Firestore library to fuel your application's growth!
version: 0.4.5
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel
homepage: https://github.com/SupposedlySam/firefuel
documentation: https://firefuel.dev

# Flutter/Dart versions: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.2'

dependencies:
  cloud_firestore: ^6.0.0
  dartz: ^0.10.1
  equatable: ^2.0.7
  firefuel_core: ^0.1.6
  flutter:
    sdk: flutter
  stack_trace: ^1.12.1
  universal_io: ^2.2.2

dev_dependencies:
  fake_cloud_firestore: ^4.0.0 #Regression in 1.3.0 breaks ordering
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

import_sorter:
  comments: false

scripts: ../../derry.yaml
