name: firefuel
description: A Firebase Cloud Firestore library to fuel your application's growth!
version: 0.1.1
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel
homepage: https://github.com/SupposedlySam/firefuel
documentation: https://firefuel.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  cloud_firestore: ^2.5.0
  dartz: ^0.10.0
  equatable: ^2.0.3
  firefuel_core: ^0.0.1
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  universal_io: ^2.0.4

dev_dependencies:
  fake_cloud_firestore: ^1.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

import_sorter:
  comments: false

scripts: ../../derry.yaml
