name: firefuel
description: A Firebase Cloud Firestore library to fuel your application's growth!
version: 0.4.3
repository: https://github.com/SupposedlySam/firefuel/tree/main/packages/firefuel
homepage: https://github.com/SupposedlySam/firefuel
documentation: https://firefuel.dev

# Flutter/Dart versions: https://docs.flutter.dev/development/tools/sdk/releases?tab=macos
environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.2'

dependencies:
  cloud_firestore: ^5.5.0
  dartz: ^0.10.0
  equatable: ^2.0.5
  firefuel_core: ^0.1.0
  flutter:
    sdk: flutter
  stack_trace: ^1.10.0
  universal_io: ^2.0.4

dev_dependencies:
  fake_cloud_firestore: ^3.1.0 #Regression in 1.3.0 breaks ordering
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^6.0.0

import_sorter:
  comments: false

scripts: ../../derry.yaml
