name: firefuel_env
description: A Firebase Cloud Firestore project to easily configure your environments
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

import_sorter:
  comments: false

scripts: ../../derry.yaml
