name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  cloud_firestore: ^2.5.3
  fake_cloud_firestore: ^1.1.3
  firebase_core: ^1.7.0
  firefuel:
    path: ../../../firefuel
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true
