// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firefuel_counter/firefuel_counter.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0zClB6tz9MqN3cStQDk2Xlg8CBrTNZ2g',
    appId: '1:1056035537569:web:8d5416f28c1609dd0926e0',
    messagingSenderId: '1056035537569',
    projectId: 'firefuel-starter',
    authDomain: 'firefuel-starter.firebaseapp.com',
    storageBucket: 'firefuel-starter.appspot.com',
    measurementId: 'G-6W2Q7DDRHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWqYRFSwpRkVnR5Twbbid-joPWkrcqD_w',
    appId: '1:1056035537569:android:157320e01c0550120926e0',
    messagingSenderId: '1056035537569',
    projectId: 'firefuel-starter',
    storageBucket: 'firefuel-starter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7U2x58SCdL5OEIJqAviOj5LAkK5PGIs',
    appId: '1:1056035537569:ios:8f2cc458f79f95f10926e0',
    messagingSenderId: '1056035537569',
    projectId: 'firefuel-starter',
    storageBucket: 'firefuel-starter.appspot.com',
    iosClientId:
        '1056035537569-5jv61q295g3vggch97o3qq9noisuk4g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7U2x58SCdL5OEIJqAviOj5LAkK5PGIs',
    appId: '1:1056035537569:ios:29f729e9e90dc2a80926e0',
    messagingSenderId: '1056035537569',
    projectId: 'firefuel-starter',
    storageBucket: 'firefuel-starter.appspot.com',
    iosClientId:
        '1056035537569-2t6i4p70kbl1hrl25s7omd7kfrcdcpc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCounter',
  );
}
