name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  fake_cloud_firestore: ^1.1.3
  firefuel_counter:
    path: ./packages/firefuel_counter
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0

dev_dependencies:
  bloc_test: ^8.2.0
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter:
  uses-material-design: true


import_sorter:
  comments: false