name: firefuel_example
description: A playground example for Firefuel APIs.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fake_cloud_firestore: ^4.1.0+1
  firefuel:
    path: ..
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

import_sorter:
  comments: false
