name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  bloc: ^8.1.0
  fake_cloud_firestore: ^2.1.0
  firefuel_counter:
    path: ./packages/firefuel_counter
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  firefuel:
    path: ..

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

import_sorter:
  comments: false
